name: Cloudly
version: ${version}
main: de.cloudly.CloudlyPaper
author: Phantom
description: Privates Server-Management Plugin für Paper 1.21+
api-version: 1.21
load: STARTUP

commands:
  cloudly:
    description: Main command for Cloudly plugin
    usage: /cloudly <subcommand>
  whitelist:
    description: Disabled vanilla whitelist command - redirects to Cloudly whitelist
    usage: /cloudly whitelist <subcommand>
    permission: cloudly.whitelist

permissions:
  cloudly.*:
    description: All Cloudly permissions
    default: false
    children:
      cloudly.admin: true
      cloudly.whitelist: true
  
  cloudly.admin:
    description: Allows the player to manage the server.
    default: op
  
  cloudly.whitelist:
    description: Allows the player to manage the whitelist.
    default: op
