name: Cloudly
version: ${version}
main: de.cloudly.CloudlyPaper
author: Phantom
description: Privates Server-Management Plugin für Paper 1.21+
api-version: 1.21
load: STARTUP

commands:
  cloudly:
    description: Main command for Cloudly plugin
    usage: /cloudly <subcommand>
  whitelist:
    description: Disabled vanilla whitelist command - redirects to Cloudly whitelist
    usage: /cloudly whitelist <subcommand>
    permission: cloudly.whitelist

permissions:
  cloudly.*:
    description: All Cloudly permissions
    default: false
    children:
      cloudly.admin: true
      cloudly.whitelist: true
      cloudly.moderation: true
      cloudly.discord.manage: true
  
  cloudly.admin:
    description: Allows the player to manage the server.
    default: op
  
  cloudly.whitelist:
    description: Allows the player to manage the whitelist.
    default: op
    children:
      cloudly.whitelist.remove: true

  cloudly.whitelist.remove:
    description: Allows removing players from the whitelist.
    default: op

  cloudly.discord.manage:
    description: Allows managing Discord links of other players.
    default: op

  cloudly.moderation:
    description: Allows access to the moderation toolset.
    default: op
    children:
      cloudly.moderation.kick: true
      cloudly.moderation.tempban: true
      cloudly.moderation.permaban: true
      cloudly.discord.manage: true

  cloudly.moderation.kick:
    description: Allows kicking players via the admin tools.
    default: op

  cloudly.moderation.tempban:
    description: Allows issuing temporary bans via the admin tools.
    default: op

  cloudly.moderation.permaban:
    description: Allows issuing permanent bans via the admin tools.
    default: op
